<?php
$root=dirname(__DIR__,4);$_SERVER['REQUEST_SCHEME']='https';$_SERVER['HTTP_HOST']='monasbat.test';require_once $root.'/wp-load.php';
$local=defined('DB_NAME')&&DB_NAME==='monasbat'&&stripos(str_replace('\\','/',$root),'/laragon/www/monasbat')!==false&&wp_get_environment_type()!=='production';if(!$local){fwrite(STDERR,"ABORT local guard\n");exit(2);}global$wpdb;$pass=0;$total=0;$ids=[];$events=[];$syncIds=[];function p5($l,$a,$e){global$pass,$total;$total++;if($a===$e){$pass++;echo"PASS $l\n";}else echo"FAIL $l expected=".var_export($e,true)." actual=".var_export($a,true)."\n";}
$merchant=random_int(700000000,799999999);$customer=random_int(800000000,899999999);$flagKey=PGE_Salla_Not_Member_Removal_Feature::OPTION_NAME;$oldFlag=get_option($flagKey,'__missing__');
function p5a($state,$source='salla',$merchant=0,$customer=0){global$ids;$uuid=wp_generate_uuid4();$r=PGE_Catalog_Activation_Repository::create_preparing(['activation_id'=>$uuid,'user_id'=>1,'plan_id'=>1,'tier_id'=>1,'plan_key'=>'halwa_plus','tier_key'=>'p5','activation_source'=>$source,'idempotency_key'=>($source==='salla'?'salla:'.$merchant.':':'manual:').wp_generate_uuid4(),'external_order_id'=>$source==='salla'?wp_generate_uuid4():null,'projection_snapshot'=>'{}']);$id=(int)$r['id'];$ids[]=$id;if($source==='salla')PGE_Catalog_Provider_Origin_Repository::create($id,'salla',$merchant,(string)$customer,wp_generate_uuid4());PGE_Catalog_Activation_Repository::compare_and_swap_state($id,'preparing',1,$state,['activated_at'=>current_time('mysql',true)]);return$id;}
try{
 $a=p5a('active_bound','salla',$merchant,$customer);$b=p5a('active_unbound','salla',$merchant,$customer);$r=PGE_Salla_Plus_Eligibility_Resolver::recompute_and_project($merchant,$customer);p5('two active eligible',$r['active_activation_count'],2);p5('desired member',$r['desired_state'],'member');$syncIds[]=(int)$r['projection']['id'];$row=PGE_Salla_Membership_Sync_Store::get($syncIds[0]);$rev1=(int)$row['desired_revision'];
 $ar=PGE_Catalog_Activation_Repository::find_by_id($a);PGE_Catalog_Activation_Repository::compare_and_swap_state($a,'active_bound',(int)$ar['revision'],'ended',['ended_at'=>current_time('mysql',true)]);$r=PGE_Salla_Plus_Eligibility_Resolver::recompute_and_project($merchant,$customer);p5('A ended B active eligible',$r['eligible'],true);p5('member idempotent revision',(int)PGE_Salla_Membership_Sync_Store::get($syncIds[0])['desired_revision'],$rev1);
 $br=PGE_Catalog_Activation_Repository::find_by_id($b);PGE_Catalog_Activation_Repository::compare_and_swap_state($b,'active_unbound',(int)$br['revision'],'ended',['ended_at'=>current_time('mysql',true)]);$r=PGE_Salla_Plus_Eligibility_Resolver::recompute_and_project($merchant,$customer);p5('last ended ineligible',$r['eligible'],false);p5('desired not member',$r['desired_state'],'not_member');$row=PGE_Salla_Membership_Sync_Store::get($syncIds[0]);p5('member to not revision',(int)$row['desired_revision'],$rev1+1);
 $c=p5a('active_unbound','salla',$merchant,$customer);$r=PGE_Salla_Plus_Eligibility_Resolver::recompute_and_project($merchant,$customer);p5('new active restores member',$r['desired_state'],'member');p5('not to member revision',(int)PGE_Salla_Membership_Sync_Store::get($syncIds[0])['desired_revision'],$rev1+2);
 $manual=p5a('active_bound','manual');$other=PGE_Salla_Plus_Eligibility_Resolver::resolve($merchant+1,$customer);p5('merchant isolation',$other['eligible'],false);$other=PGE_Salla_Plus_Eligibility_Resolver::resolve($merchant,$customer+1);p5('customer isolation',$other['eligible'],false);$manualOnly=PGE_Salla_Plus_Eligibility_Resolver::resolve($merchant+2,$customer+2);p5('manual excluded',$manualOnly['eligible'],false);
 $cr=PGE_Catalog_Activation_Repository::find_by_id($c);PGE_Catalog_Activation_Repository::compare_and_swap_state($c,'active_unbound',(int)$cr['revision'],'ended');PGE_Salla_Plus_Eligibility_Resolver::recompute_and_project($merchant,$customer);update_option($flagKey,1,false);$http=0;$hook=function($pre,$args){$GLOBALS['p5_http'][]=$args['method']??'GET';return new WP_Error('blocked');};$GLOBALS['p5_http']=[];add_filter('pre_http_request',$hook,10,2);PGE_Salla_Membership_Sync_Worker::run_batch(10);remove_filter('pre_http_request',$hook,10);p5('not member issues no destructive PUT without usable transport',in_array('PUT',$GLOBALS['p5_http'],true),false);$row=PGE_Salla_Membership_Sync_Store::get($syncIds[0]);p5('failed pre-GET schedules retry without PUT',$row['last_error_code'],'remote_http_error');
}finally{foreach($syncIds as$id)$wpdb->delete(PGE_Salla_Sync_Schema::table_name(),['id'=>$id],['%d']);foreach($ids as$id){$wpdb->delete(PGE_Catalog_Activation_Schema::events_table(),['catalog_activation_id'=>$id],['%d']);$wpdb->delete(PGE_Catalog_Activation_Schema::origins_table(),['catalog_activation_id'=>$id],['%d']);$wpdb->delete(PGE_Catalog_Activation_Schema::activations_table(),['id'=>$id],['%d']);}if($oldFlag==='__missing__')delete_option($flagKey);else update_option($flagKey,$oldFlag,false);}
echo"$pass/$total passed\n";exit($pass===$total?0:1);
