<?php
/** Local MySQL integration proof for DEC-PLUS-MIG-01. Uses exact isolated IDs and cleans only its fixtures. */
$root=dirname(__DIR__,4);$_SERVER['REQUEST_SCHEME']='https';$_SERVER['HTTP_HOST']='monasbat.test';require_once $root.'/wp-load.php';
$site=(string)get_option('siteurl','');$local=defined('DB_NAME')&&DB_NAME==='monasbat'&&preg_match('#^https?://[^/]+\.test(?:/|$)#',$site)&&stripos(str_replace('\\','/',$root),'/laragon/www/monasbat')!==false&&function_exists('wp_get_environment_type')&&wp_get_environment_type()!=='production';if(!$local){fwrite(STDERR,"ABORT: local guard failed; no writes.\n");exit(2);}global$wpdb;
require_once dirname(__DIR__).'/includes/class-pge-dec-plus-mig-01-backfill.php';
$pass=0;$total=0;$createdUser=false;$activationDbId=0;$metaKeys=[
'_mon_package_source'=>'catalog','_mon_catalog_plan_id'=>2,'_mon_catalog_tier_id'=>6,'_mon_catalog_plan_key'=>'halwa_plus','_mon_catalog_tier_key'=>'guests_100','_mon_package_status'=>'active','_mon_credit_cycle_id'=>'6daa5ee5-5bda-43a6-a392-ad75402b8c21','_mon_last_order_id'=>'1576373696','_mon_salla_product_id'=>'1539650850','_mon_package_activated_at'=>'2026-09-15 20:12:37','_mon_package_price'=>'0.00','_mon_package_currency'=>'SAR','_mon_guest_limit'=>100,'_mon_event_quota_mode'=>'limited','_mon_event_quota_limit'=>1,'_mon_invitation_credit_total'=>100,'_mon_invitation_credit_used'=>0,'_mon_replacement_credit_total'=>40,'_mon_replacement_credit_used'=>0];
function migcheck($l,$a,$e){global$pass,$total;$total++;if($a===$e){$pass++;echo"PASS $l\n";}else echo"FAIL $l expected=".var_export($e,true)." actual=".var_export($a,true)."\n";}
try{
 if(get_user_by('id',380)||PGE_Catalog_Activation_Repository::find_by_activation_id(PGE_DEC_Plus_MIG_01_Backfill::ACTIVATION_ID)||PGE_Catalog_Activation_Repository::find_by_idempotency_key(PGE_DEC_Plus_MIG_01_Backfill::IDEMPOTENCY_KEY)||PGE_Catalog_Provider_Origin_Repository::find_by_order('salla',392732220,'1576373696')||PGE_Catalog_Order_Revocation_Repository::find('salla',392732220,'1576373696')){fwrite(STDERR,"ABORT: isolated identities already exist; no writes.\n");exit(2);}
 $now=gmdate('Y-m-d H:i:s');$ok=$wpdb->insert($wpdb->users,['ID'=>380,'user_login'=>'dec-plus-mig-01-test','user_pass'=>'!','user_nicename'=>'dec-plus-mig-01-test','user_email'=>'dec-plus-mig-01@example.test','user_registered'=>$now,'display_name'=>'DEC Plus MIG 01'],['%d','%s','%s','%s','%s','%s','%s']);if(!$ok)throw new RuntimeException('Unable to create isolated user 380');$createdUser=true;
 foreach($metaKeys as$key=>$value)update_user_meta(380,$key,$value);clean_user_cache(380);$before=get_user_meta(380);
 $result=PGE_DEC_Plus_MIG_01_Backfill::execute();migcheck('production service backfills',$result['result']??null,'backfilled');$activationDbId=(int)($result['catalog_activation_id']??0);$row=PGE_Catalog_Activation_Repository::find_by_id($activationDbId);$origin=PGE_Catalog_Provider_Origin_Repository::find_by_order('salla',392732220,'1576373696');
 migcheck('MySQL durable state active_unbound',$row['lifecycle_state']??null,'active_unbound');migcheck('MySQL origin belongs to activation',(int)($origin['catalog_activation_id']??0),$activationDbId);migcheck('MySQL historical timestamp',$row['activated_at']??null,'2026-09-15 20:12:37');migcheck('MySQL User Meta byte structure unchanged',get_user_meta(380),$before);migcheck('MySQL no binding',count(PGE_Catalog_Event_Binding_Repository::find_by_activation_id($activationDbId)),0);
 $replay=PGE_DEC_Plus_MIG_01_Backfill::execute();migcheck('MySQL exact replay',$replay['result']??null,'already_backfilled');migcheck('MySQL one activation',(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.PGE_Catalog_Activation_Schema::activations_table().' WHERE activation_id=%s',PGE_DEC_Plus_MIG_01_Backfill::ACTIVATION_ID)),1);migcheck('MySQL one origin',(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.PGE_Catalog_Activation_Schema::origins_table().' WHERE provider=%s AND merchant_id=%d AND external_order_id=%s','salla',392732220,'1576373696')),1);
 $durableBefore=[PGE_Catalog_Activation_Repository::find_by_id($activationDbId),PGE_Catalog_Provider_Origin_Repository::find_by_order('salla',392732220,'1576373696'),PGE_Catalog_Event_Binding_Repository::find_by_activation_id($activationDbId)];
 update_user_meta(380,'_mon_invitation_credit_used',7);update_user_meta(380,'_mon_replacement_credit_used',3);clean_user_cache(380);
 $mutableReplay=PGE_DEC_Plus_MIG_01_Backfill::execute();$durableAfter=[PGE_Catalog_Activation_Repository::find_by_id($activationDbId),PGE_Catalog_Provider_Origin_Repository::find_by_order('salla',392732220,'1576373696'),PGE_Catalog_Event_Binding_Repository::find_by_activation_id($activationDbId)];
 migcheck('MySQL replay ignores changed mutable credit User Meta',$mutableReplay['result']??null,'already_backfilled');migcheck('MySQL replay leaves durable rows byte-equivalent',$durableAfter,$durableBefore);migcheck('MySQL changed invitation credit remains untouched',get_user_meta(380,'_mon_invitation_credit_used',true),'7');migcheck('MySQL changed replacement credit remains untouched',get_user_meta(380,'_mon_replacement_credit_used',true),'3');
}finally{
 if($activationDbId){$wpdb->delete(PGE_Catalog_Activation_Schema::events_table(),['catalog_activation_id'=>$activationDbId],['%d']);$wpdb->delete(PGE_Catalog_Activation_Schema::origins_table(),['catalog_activation_id'=>$activationDbId],['%d']);$wpdb->delete(PGE_Catalog_Activation_Schema::activations_table(),['id'=>$activationDbId],['%d']);}
 if($createdUser){$wpdb->delete($wpdb->usermeta,['user_id'=>380],['%d']);$wpdb->delete($wpdb->users,['ID'=>380],['%d']);clean_user_cache(380);}
}
migcheck('cleanup removed isolated user',get_user_by('id',380),false);
migcheck('cleanup removed isolated activation',PGE_Catalog_Activation_Repository::find_by_activation_id(PGE_DEC_Plus_MIG_01_Backfill::ACTIVATION_ID),null);
migcheck('cleanup removed isolated origin',PGE_Catalog_Provider_Origin_Repository::find_by_order('salla',392732220,'1576373696'),null);
echo"\n$pass/$total passed\n";exit($pass===$total?0:1);
