<?php
define('ABSPATH', __DIR__ . '/');
class WP_Error { private $c; function __construct($c){$this->c=$c;} function get_error_code(){return $this->c;} }
function is_wp_error($v){return $v instanceof WP_Error;}
function absint($v){return abs((int)$v);}
function current_time($type,$gmt=false){return $GLOBALS['now'] ?? '2026-10-01 22:00:00';}
function add_filter($h,$c){$GLOBALS['filters'][$h][]=$c;}
function add_action($h,$c){$GLOBALS['actions'][$h][]=$c;}
function wp_next_scheduled($h){return $GLOBALS['scheduled'][$h]??false;}
function wp_schedule_event($t,$s,$h){$GLOBALS['scheduled'][$h]=[$t,$s];return true;}
function get_post($id){return !empty($GLOBALS['posts'][$id])?(object)['ID'=>$id]:null;}
function get_post_meta($id,$key,$single=true){return $GLOBALS['meta'][$id][$key]??'';}
function update_post_meta($id,$key,$value){$GLOBALS['meta'][$id][$key]=$value;return true;}
class FakeWpdb { public $queries=[],$commit_fail=false; function prepare($q,...$a){return $q;} function get_var($q){return 1;} function query($q){$this->queries[]=$q;if($q==='COMMIT'&&$this->commit_fail)return false;return 0;} }
$wpdb=new FakeWpdb();
class PGE_Catalog_Activation_Repository {
 const STATE_ACTIVE_UNBOUND='active_unbound',STATE_ACTIVE_BOUND='active_bound',STATE_ENDED='ended',STATE_REVOKED='revoked'; public static $rows=[],$updates=[],$due=[],$fail_update=false,$fail_cas=false;
 static function find_by_id($id){return self::$rows[$id]??null;}
 static function find_by_id_for_update($id){return self::find_by_id($id);}
 static function update_reconciliation($id,$rev,$m=[]){if(self::$fail_update)return['result'=>'db_error'];$r=self::$rows[$id]??null;if(!$r)return['result'=>'missing'];if($r['lifecycle_state']!=='active_bound')return['result'=>'terminal'];if($r['revision']!==$rev)return['result'=>'stale'];self::$rows[$id]=array_merge($r,$m,['revision'=>$rev+1]);self::$updates[]=$m;return['result'=>'updated','revision'=>$rev+1];}
 static function compare_and_swap_state($id,$es,$er,$ns,$m=[]){if(self::$fail_cas)return['result'=>'db_error'];$r=self::$rows[$id]??null;if(!$r)return['result'=>'missing'];if($r['lifecycle_state']!==$es||$r['revision']!==$er)return['result'=>in_array($r['lifecycle_state'],['ended','revoked'])?'terminal':'stale'];self::$rows[$id]=array_merge($r,$m,['lifecycle_state'=>$ns,'revision'=>$er+1]);return['result'=>'updated','revision'=>$er+1];}
 static function find_due_reconciliation($l=20){$GLOBALS['due_limit']=$l;return array_slice(self::$due,0,$l);}
}
class PGE_Catalog_Event_Binding_Repository { public static $rows=[]; static function find_by_event_id($id){foreach(self::$rows as$r)if($r['event_id']==$id)return$r;return null;} static function find_by_activation_id($id){return array_values(array_filter(self::$rows,fn($r)=>$r['catalog_activation_id']==$id));} static function create($a,$e){self::$rows[]=['catalog_activation_id'=>$a,'event_id'=>$e];return['result'=>'created'];} }
require_once dirname(__DIR__).'/includes/class-pge-catalog-event-lifecycle-service.php';
require_once dirname(__DIR__).'/includes/class-pge-catalog-event-binding-service.php';
$pass=0;$fail=0;function p4($n,$a,$e){global$pass,$fail;if($a===$e){$pass++;echo"PASS $n\n";}else{$fail++;echo"FAIL $n expected=".var_export($e,true)." actual=".var_export($a,true)."\n";}}
function reset4($state='active_bound',$plan='halwa_plus'){$GLOBALS['posts']=[10=>1];$GLOBALS['meta']=[10=>['_pge_event_date'=>'2026-10-01T18:00','_pge_event_activation_id'=>'a']];PGE_Catalog_Activation_Repository::$rows=[1=>['id'=>1,'activation_id'=>'a','lifecycle_state'=>$state,'revision'=>1,'plan_key'=>$plan,'next_reconcile_at'=>null,'ended_at'=>null]];PGE_Catalog_Activation_Repository::$updates=[];PGE_Catalog_Activation_Repository::$fail_update=PGE_Catalog_Activation_Repository::$fail_cas=false;PGE_Catalog_Event_Binding_Repository::$rows=[['catalog_activation_id'=>1,'event_id'=>10]];}
$t=PGE_Catalog_Event_Lifecycle_Service::resolve_times('2026-10-01 18:00');p4('Riyadh start UTC',$t['start_utc'],'2026-10-01 15:00:00');p4('end plus six hours',$t['end_utc'],'2026-10-01 21:00:00');
date_default_timezone_set('Pacific/Honolulu');$t=PGE_Catalog_Event_Lifecycle_Service::resolve_times('2026-10-01T18:00');p4('server timezone independent',$t['end_utc'],'2026-10-01 21:00:00');
p4('missing rejected',PGE_Catalog_Event_Lifecycle_Service::resolve_times('')->get_error_code(),'event_date_missing');p4('malformed rejected',PGE_Catalog_Event_Lifecycle_Service::resolve_times('tomorrow')->get_error_code(),'event_date_invalid');p4('impossible rejected',PGE_Catalog_Event_Lifecycle_Service::resolve_times('2026-02-30T10:00')->get_error_code(),'event_date_invalid');
reset4();$r=PGE_Catalog_Event_Lifecycle_Service::schedule_bound_event(1,10,'2026-10-01 10:00:00');p4('binding schedules',$r['result'],'updated');p4('scheduled exact end',PGE_Catalog_Activation_Repository::$rows[1]['next_reconcile_at'],'2026-10-01 21:00:00');
$GLOBALS['meta'][10]['_pge_event_date']='2026-10-02T18:00';$r=PGE_Catalog_Event_Lifecycle_Service::reschedule_event(10);p4('edit later reschedules',PGE_Catalog_Activation_Repository::$rows[1]['next_reconcile_at'],'2026-10-02 21:00:00');
$GLOBALS['meta'][10]['_pge_event_date']='2026-10-01T17:00';PGE_Catalog_Event_Lifecycle_Service::reschedule_event(10);p4('edit earlier reschedules',PGE_Catalog_Activation_Repository::$rows[1]['next_reconcile_at'],'2026-10-01 20:00:00');
reset4();$GLOBALS['meta'][10]['_pge_event_date']='bad';$r=PGE_Catalog_Event_Lifecycle_Service::schedule_bound_event(1,10,'2026-10-01 10:00:00');p4('bad date stays active',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'active_bound');p4('bad date durable error',PGE_Catalog_Activation_Repository::$rows[1]['last_error_code'],'event_date_invalid');
reset4();$r=PGE_Catalog_Event_Lifecycle_Service::reconcile(1,'2026-10-01 22:00:00');p4('due ends',$r['result'],'updated');p4('state ended',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'ended');p4('ended actual instant',PGE_Catalog_Activation_Repository::$rows[1]['ended_at'],'2026-10-01 22:00:00');p4('due cleared',PGE_Catalog_Activation_Repository::$rows[1]['next_reconcile_at'],null);
$rev=PGE_Catalog_Activation_Repository::$rows[1]['revision'];$r=PGE_Catalog_Event_Lifecycle_Service::reconcile(1,'2026-10-01 23:00:00');p4('second worker noop',$r['result'],'noop');p4('no double revision',PGE_Catalog_Activation_Repository::$rows[1]['revision'],$rev);
$GLOBALS['meta'][10]['_pge_event_date']='2027-01-01T18:00';PGE_Catalog_Event_Lifecycle_Service::reschedule_event(10);p4('ended edit no revival',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'ended');p4('ended timestamp stable',PGE_Catalog_Activation_Repository::$rows[1]['ended_at'],'2026-10-01 22:00:00');
reset4('revoked');$r=PGE_Catalog_Event_Lifecycle_Service::reschedule_event(10);p4('revoked edit terminal noop',$r['result'],'terminal_noop');p4('revoked stable',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'revoked');
reset4();$r=PGE_Catalog_Event_Lifecycle_Service::reconcile(1,'2026-10-01 20:00:00');p4('not due metadata update',$r['result'],'updated');p4('not due remains active',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'active_bound');
reset4();unset($GLOBALS['posts'][10]);$r=PGE_Catalog_Event_Lifecycle_Service::reconcile(1,'2026-10-01 22:00:00');p4('deleted remains active',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'active_bound');p4('deleted durable error',PGE_Catalog_Activation_Repository::$rows[1]['last_error_code'],'bound_event_missing');
reset4('active_bound','standard');$r=PGE_Catalog_Event_Lifecycle_Service::reconcile(1,'2026-10-01 22:00:00');p4('non Plus excluded',$r['result'],'not_applicable');p4('non Plus active',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'active_bound');
reset4();$GLOBALS['meta'][10]['_pge_event_date']='2027-01-01T18:00';$r=PGE_Catalog_Event_Lifecycle_Service::reconcile(1,'2026-10-01 22:00:00');p4('stale due rereads future date',$r['result'],'updated');p4('future race does not end',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'active_bound');
reset4();$r=PGE_Catalog_Event_Lifecycle_Service::update_event_date(10,'2027-02-01T18:00','2026-10-01 22:00:00');p4('date edit writes under lifecycle API',$GLOBALS['meta'][10]['_pge_event_date'],'2027-02-01T18:00');p4('date edit schedules under same lock',PGE_Catalog_Activation_Repository::$rows[1]['next_reconcile_at'],'2027-02-01 21:00:00');
PGE_Catalog_Activation_Repository::$due=array_fill(0,60,PGE_Catalog_Activation_Repository::$rows[1]);PGE_Catalog_Event_Lifecycle_Service::run_due();p4('batch limit fifty',$GLOBALS['due_limit'],50);
$GLOBALS['scheduled']=[];$GLOBALS['filters']=$GLOBALS['actions']=[];PGE_Catalog_Event_Lifecycle_Service::register();PGE_Catalog_Event_Lifecycle_Service::ensure_scheduled();$one=count($GLOBALS['scheduled']);PGE_Catalog_Event_Lifecycle_Service::ensure_scheduled();p4('cron schedule idempotent',count($GLOBALS['scheduled']),$one);p4('five minute recurrence',$GLOBALS['scheduled'][PGE_Catalog_Event_Lifecycle_Service::CRON_HOOK][1],PGE_Catalog_Event_Lifecycle_Service::CRON_SCHEDULE);
reset4('active_unbound');PGE_Catalog_Event_Binding_Repository::$rows=[];$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p4('initial bind anchored',$r['result']??'','bound');p4('initial bind exact schedule',PGE_Catalog_Activation_Repository::$rows[1]['next_reconcile_at'],'2026-10-01 21:00:00');
reset4('active_unbound');PGE_Catalog_Event_Binding_Repository::$rows=[];$GLOBALS['meta'][10]['_pge_event_date']='';$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p4('missing date bind succeeds',$r['result']??'','bound');p4('missing date retry anchor non-null',!empty(PGE_Catalog_Activation_Repository::$rows[1]['next_reconcile_at']),true);p4('missing date error',PGE_Catalog_Activation_Repository::$rows[1]['last_error_code'],'event_date_missing');
reset4('active_unbound');PGE_Catalog_Event_Binding_Repository::$rows=[];PGE_Catalog_Activation_Repository::$fail_cas=true;$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p4('anchor DB failure reported',is_wp_error($r)?$r->get_error_code():'','event_binding_cas_db_error');p4('failed anchor state unchanged',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'active_unbound');
reset4();$before=PGE_Catalog_Activation_Repository::$rows[1]['revision'];$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p4('legacy NULL anchor repaired',$r['lifecycle']['result']??'','repaired');p4('repair creates anchor',PGE_Catalog_Activation_Repository::$rows[1]['next_reconcile_at'],'2026-10-01 21:00:00');$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p4('repeat repair already anchored',$r['lifecycle']['result']??'','already_anchored');p4('repeat repair revision stable',PGE_Catalog_Activation_Repository::$rows[1]['revision'],$before+1);
reset4('active_unbound');PGE_Catalog_Event_Binding_Repository::$rows=[];$wpdb->commit_fail=true;$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p4('commit failure is storage uncertain',is_wp_error($r)?$r->get_error_code():'','event_binding_storage_uncertain');$wpdb->commit_fail=false;
echo "RESULT: $pass PASS, $fail FAIL\n";exit($fail?1:0);
