<?php
$root=dirname(__DIR__,4);$_SERVER['REQUEST_SCHEME']='https';$_SERVER['HTTP_HOST']='monasbat.test';require_once $root.'/wp-load.php';
$site=(string)get_option('siteurl','');$local=defined('DB_NAME')&&DB_NAME==='monasbat'&&preg_match('#^https?://[^/]+\.test(?:/|$)#',$site)&&stripos(str_replace('\\','/',$root),'/laragon/www/monasbat')!==false&&function_exists('wp_get_environment_type')&&wp_get_environment_type()!=='production';if(!$local){fwrite(STDERR,"ABORT: local guard failed; no writes.\n");exit(2);}global$wpdb;$pass=0;$total=0;function p4m($l,$a,$e){global$pass,$total;$total++;if($a===$e){$pass++;echo"PASS: $l\n";}else echo"FAIL: $l expected=".var_export($e,true)." actual=".var_export($a,true)."\n";}
$tag='phase4-'.bin2hex(random_bytes(5));$user=0;$plan=0;$tier=0;$events=[];$activationIds=[];$failureTrigger='';
try{
 $user=wp_insert_user(['user_login'=>$tag,'user_pass'=>wp_generate_password(24,true,true),'user_email'=>$tag.'@example.test']);$made=PGE_Catalog::create_plan(['plan_key'=>'halwa_plus','name'=>'Phase 4 Plus','plan_type'=>'personal','status'=>'active','sort_order'=>0,'features'=>[]]);$plan=(int)($made['id']??0);$wpdb->insert($wpdb->prefix.'mon_plan_tiers',['plan_id'=>$plan,'tier_key'=>'phase4','name'=>'Phase 4','price'=>'10','currency'=>'SAR','status'=>'active','sort_order'=>0,'event_quota_mode'=>'limited','event_quota_limit'=>1],['%d','%s','%s','%s','%s','%s','%d','%s','%d']);$tier=(int)$wpdb->insert_id;
 $activation=PGE_Catalog_Activation_Service::activate((int)$user,$plan,$tier,['source'=>'manual','operation_id'=>wp_generate_uuid4()]);$id=(int)$activation['catalog_activation_id'];$activationIds[]=$id;$event=wp_insert_post(['post_type'=>'pge_event','post_status'=>'private','post_author'=>(int)$user,'post_title'=>$tag,'meta_input'=>['_pge_event_activation_id'=>$activation['activation_id'],'_pge_event_creation_operation_id'=>wp_generate_uuid4(),'_pge_event_date'=>'2026-10-01T18:00']]);$events[]=$event;
 $bound=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::find_by_id($id),$event);p4m('binding succeeds',$bound['result']??'','bound');$row=PGE_Catalog_Activation_Repository::find_by_id($id);p4m('binding schedules UTC end',$row['next_reconcile_at'],'2026-10-01 21:00:00');p4m('private event remains bound',$row['lifecycle_state'],'active_bound');
 update_post_meta($event,'_pge_event_date','2026-10-02T18:00');PGE_Catalog_Event_Lifecycle_Service::reschedule_event($event,'2026-10-01 20:00:00');$row=PGE_Catalog_Activation_Repository::find_by_id($id);p4m('edit later persists schedule',$row['next_reconcile_at'],'2026-10-02 21:00:00');
 $notDue=PGE_Catalog_Event_Lifecycle_Service::reconcile($id,'2026-10-02 20:00:00');p4m('not due updates only',$notDue['result'],'updated');p4m('not due stays active',PGE_Catalog_Activation_Repository::find_by_id($id)['lifecycle_state'],'active_bound');
 $lock=PGE_Catalog_Event_Binding_Service::lock_name($activation['activation_id']);$hp=explode(':',DB_HOST,2);$db2=@new mysqli($hp[0],DB_USER,DB_PASSWORD,DB_NAME,isset($hp[1])?(int)$hp[1]:3306);if($db2->connect_errno)throw new RuntimeException('second local connection unavailable');$escaped=$db2->real_escape_string($lock);$held=$db2->query("SELECT GET_LOCK('$escaped',0) acquired")->fetch_assoc();p4m('competing worker owns lifecycle lock',(int)$held['acquired'],1);$blocked=PGE_Catalog_Event_Lifecycle_Service::reconcile($id,'2026-10-02 22:15:00');p4m('second reconciler cannot enter',is_wp_error($blocked)?$blocked->get_error_code():'','activation_lock_unavailable');p4m('blocked worker cannot end',PGE_Catalog_Activation_Repository::find_by_id($id)['lifecycle_state'],'active_bound');$db2->query("SELECT RELEASE_LOCK('$escaped')");$db2->close();
 $ended=PGE_Catalog_Event_Lifecycle_Service::reconcile($id,'2026-10-02 22:15:00');p4m('due CAS updates',$ended['result'],'updated');$row=PGE_Catalog_Activation_Repository::find_by_id($id);p4m('due becomes ended',$row['lifecycle_state'],'ended');p4m('ended_at actual run',$row['ended_at'],'2026-10-02 22:15:00');p4m('schedule cleared',$row['next_reconcile_at'],null);$revision=(int)$row['revision'];
 $again=PGE_Catalog_Event_Lifecycle_Service::reconcile($id,'2026-10-02 23:00:00');p4m('repeat reconciler noop',$again['result'],'noop');p4m('repeat does not revise',(int)PGE_Catalog_Activation_Repository::find_by_id($id)['revision'],$revision);update_post_meta($event,'_pge_event_date','2027-01-01T18:00');PGE_Catalog_Event_Lifecycle_Service::reschedule_event($event);$row=PGE_Catalog_Activation_Repository::find_by_id($id);p4m('terminal edit cannot revive',$row['lifecycle_state'],'ended');p4m('terminal edit keeps ended_at',$row['ended_at'],'2026-10-02 22:15:00');
 $uuid=wp_generate_uuid4();$created=PGE_Catalog_Activation_Repository::create_preparing(['activation_id'=>$uuid,'user_id'=>$user,'plan_id'=>$plan,'tier_id'=>$tier,'plan_key'=>'halwa_plus','tier_key'=>'phase4','activation_source'=>'manual','idempotency_key'=>'manual:'.wp_generate_uuid4(),'external_order_id'=>null,'projection_snapshot'=>'{"meta":{},"delete":[]}']);$badId=(int)$created['id'];$activationIds[]=$badId;PGE_Catalog_Activation_Repository::compare_and_swap_state($badId,'preparing',1,'active_unbound');$badEvent=wp_insert_post(['post_type'=>'pge_event','post_status'=>'publish','post_author'=>$user,'post_title'=>$tag.' bad','meta_input'=>['_pge_event_activation_id'=>$uuid,'_pge_event_creation_operation_id'=>wp_generate_uuid4(),'_pge_event_date'=>'2026-02-30T10:00']]);$events[]=$badEvent;$bad=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::find_by_id($badId),$badEvent);$badRow=PGE_Catalog_Activation_Repository::find_by_id($badId);p4m('malformed binding still durable',$bad['result']??'','bound');p4m('malformed remains active',$badRow['lifecycle_state'],'active_bound');p4m('malformed records durable error',$badRow['last_error_code'],'event_date_invalid');p4m('malformed schedules retry',$badRow['next_reconcile_at']!==null,true);
 $failUuid=wp_generate_uuid4();$madeFail=PGE_Catalog_Activation_Repository::create_preparing(['activation_id'=>$failUuid,'user_id'=>$user,'plan_id'=>$plan,'tier_id'=>$tier,'plan_key'=>'halwa_plus','tier_key'=>'phase4','activation_source'=>'manual','idempotency_key'=>'manual:'.wp_generate_uuid4(),'external_order_id'=>null,'projection_snapshot'=>'{"meta":{},"delete":[]}']);$failId=(int)$madeFail['id'];$activationIds[]=$failId;PGE_Catalog_Activation_Repository::compare_and_swap_state($failId,'preparing',1,'active_unbound');$failEvent=wp_insert_post(['post_type'=>'pge_event','post_status'=>'publish','post_author'=>$user,'post_title'=>$tag.' fail','meta_input'=>['_pge_event_activation_id'=>$failUuid,'_pge_event_creation_operation_id'=>wp_generate_uuid4(),'_pge_event_date'=>'2026-10-01T18:00']]);$events[]=$failEvent;$failureTrigger='pge_p4_fail_'.bin2hex(random_bytes(4));$table=PGE_Catalog_Activation_Schema::activations_table();$safeUuid=esc_sql($failUuid);$createdTrigger=$wpdb->query("CREATE TRIGGER `$failureTrigger` BEFORE UPDATE ON `$table` FOR EACH ROW BEGIN IF OLD.activation_id = '$safeUuid' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'phase4 injected lifecycle failure'; END IF; END");p4m('failure trigger created',$createdTrigger!==false,true);$wpdb->suppress_errors(true);$failedBind=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::find_by_id($failId),$failEvent);$wpdb->suppress_errors(false);p4m('lifecycle write failure reported',is_wp_error($failedBind)?$failedBind->get_error_code():'','event_binding_cas_db_error');p4m('rollback removes binding',PGE_Catalog_Event_Binding_Repository::find_by_event_id($failEvent),null);$failRow=PGE_Catalog_Activation_Repository::find_by_id($failId);p4m('rollback restores prior state',$failRow['lifecycle_state'],'active_unbound');p4m('no active bound without anchor',$failRow['next_reconcile_at'],null);$wpdb->query("DROP TRIGGER IF EXISTS `$failureTrigger`");$failureTrigger='';
}finally{if($failureTrigger){$wpdb->query("DROP TRIGGER IF EXISTS `$failureTrigger`");}foreach($events as$event)wp_delete_post($event,true);foreach($activationIds as$id){$wpdb->delete(PGE_Catalog_Activation_Schema::events_table(),['catalog_activation_id'=>$id],['%d']);$wpdb->delete(PGE_Catalog_Activation_Schema::activations_table(),['id'=>$id],['%d']);}if($tier)PGE_Catalog::delete_tier($tier);if($plan)PGE_Catalog::delete_plan($plan);if($user&&!is_wp_error($user)){require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user((int)$user);}}
echo"\n$pass/$total passed\n";exit($pass===$total?0:1);
