<?php
define('ABSPATH',__DIR__.'/');define('ARRAY_A','ARRAY_A');function absint($v){return abs((int)$v);}class FakeP5Db{public$count=0,$queries=[],$fail_count=false,$last_error='';function prepare($q,...$a){return vsprintf(str_replace(['%s','%d'],["'%s'",'%d'],$q),$a);}function get_var($q){$this->queries[]=$q;if(strpos($q,'GET_LOCK')!==false||strpos($q,'RELEASE_LOCK')!==false)return 1;if($this->fail_count){$this->last_error='injected query failure';return false;}return $this->count;}function query($q){$this->queries[]=$q;return 1;}function get_results($q,$m){return[];}}$wpdb=new FakeP5Db();
if(!isset($GLOBALS['p5_options']))$GLOBALS['p5_options']=[];function get_option($k,$d=false){return array_key_exists($k,$GLOBALS['p5_options'])?$GLOBALS['p5_options'][$k]:$d;}function update_option($k,$v,$autoload=null){$GLOBALS['p5_options'][$k]=$v;return true;}
class PGE_Catalog_Activation_Schema{static function activations_table(){return'a';}static function origins_table(){return'o';}}class PGE_Catalog_Activation_Repository{const STATE_ACTIVE_UNBOUND='active_unbound',STATE_ACTIVE_BOUND='active_bound';}class PGE_Catalog_Provider_Origin_Repository{static$origin=null;static function find_by_activation_and_provider($id,$p){return self::$origin;}}class PGE_Salla_Membership_Sync_Store{const DESIRED_MEMBER='member',DESIRED_NOT_MEMBER='not_member';static$calls=[];static function identity_lock_name($m,$c,$g){return"l:$m:$c:$g";}static function request_state_locked($m,$c,$g,$s){self::$calls[]=[$m,$c,$g,$s];return['result'=>'updated','desired_revision'=>2];}}
require_once dirname(__DIR__).'/includes/class-pge-salla-plus-eligibility-resolver.php';$p=0;$f=0;function ck($n,$a,$e){global$p,$f;if($a===$e){$p++;echo"PASS $n\n";}else{$f++;echo"FAIL $n\n";}}
$wpdb->count=2;$r=PGE_Salla_Plus_Eligibility_Resolver::resolve(10,20);ck('aggregate count',$r['active_activation_count'],2);ck('aggregate eligible',$r['eligible'],true);ck('identity echoed',[$r['merchant_id'],$r['salla_customer_id']],[10,20]);
$wpdb->fail_count=true;$r=PGE_Salla_Plus_Eligibility_Resolver::resolve(10,20);ck('query failure is non-authoritative',$r['authoritative'],false);ck('query failure is not ineligible',$r['eligible'],null);ck('query failure is explicit',$r['reason'],'eligibility_query_failed');$wpdb->fail_count=false;$wpdb->last_error='';
$wpdb->count=0;PGE_Salla_Membership_Sync_Store::$calls=[];$r=PGE_Salla_Plus_Eligibility_Resolver::recompute_and_project(10,20);ck('ineligible projects not member',$r['desired_state'],'not_member');ck('not member exact identity',PGE_Salla_Membership_Sync_Store::$calls[0],[10,20,225189340,'not_member']);ck('lock acquired before count',strpos($wpdb->queries[count($wpdb->queries)-3],'GET_LOCK')!==false,true);
$wpdb->count=1;$r=PGE_Salla_Plus_Eligibility_Resolver::recompute_and_project(10,20);ck('new active recomputation member',$r['desired_state'],'member');ck('member projected',end(PGE_Salla_Membership_Sync_Store::$calls),[10,20,225189340,'member']);
PGE_Catalog_Provider_Origin_Repository::$origin=['merchant_id'=>10,'external_customer_id'=>'20'];$r=PGE_Salla_Plus_Eligibility_Resolver::project_activation(9);ck('activation uses durable origin',$r['desired_state'],'member');PGE_Catalog_Provider_Origin_Repository::$origin=null;ck('manual/no origin excluded',PGE_Salla_Plus_Eligibility_Resolver::project_activation(9)['result'],'not_applicable');
$life=file_get_contents(dirname(__DIR__).'/includes/class-pge-catalog-event-lifecycle-service.php');$activation=file_get_contents(dirname(__DIR__).'/includes/class-pge-catalog-activation-service.php');$handler=file_get_contents(dirname(__DIR__).'/includes/class-salla-handler.php');ck('ended mutation uses identity boundary',strpos($life,'with_activation_identity_lock')!==false,true);ck('ended projection remains inside identity boundary',strpos($life,'recompute_and_project_locked')!==false,true);ck('activation mutation uses identity boundary',strpos($activation,'with_activation_identity_lock')!==false,true);ck('activation projects before identity unlock',strpos($activation,'recompute_and_project_locked')!==false,true);ck('activation aggregate integration present',strpos($handler,'PGE_Salla_Plus_Eligibility_Resolver::recompute_and_project')!==false,true);
ck('canonical identity lock boundary exists',method_exists('PGE_Salla_Plus_Eligibility_Resolver','with_identity_lock'),true);
ck('activation mutation boundary exists',method_exists('PGE_Salla_Plus_Eligibility_Resolver','with_activation_identity_lock'),true);
ck('locked authoritative recompute exists',method_exists('PGE_Salla_Plus_Eligibility_Resolver','recompute_and_project_locked'),true);
$resolver=file_get_contents(dirname(__DIR__).'/includes/class-pge-salla-plus-eligibility-resolver.php');
ck('recovery uses durable cursor',strpos($resolver,'RECOVERY_CURSOR_OPTION')!==false,true);
ck('recovery query advances past cursor',strpos($resolver,'HAVING MIN(o.id) > %d')!==false,true);
echo"RESULT: $p PASS, $f FAIL\n";exit($f?1:0);
