<?php
/** Local-only MySQL proof for Phase 7 removal snapshot durability. */
$root=dirname(__DIR__,4);$_SERVER['REQUEST_SCHEME']='https';$_SERVER['HTTP_HOST']='monasbat.test';require_once $root.'/wp-load.php';
$site=(string)get_option('siteurl','');$local=defined('DB_NAME')&&DB_NAME==='monasbat'&&preg_match('#^https?://[^/]+\.test(?:/|$)#',$site)&&stripos(str_replace('\\','/',$root),'/laragon/www/monasbat')!==false&&wp_get_environment_type()!=='production';if(!$local){fwrite(STDERR,"ABORT local guard\n");exit(2);}global$wpdb;$p=0;$n=0;$ids=[];$renamed=false;function p7m($l,$a,$e){global$p,$n;$n++;if($a===$e){$p++;echo"PASS $l\n";}else echo"FAIL $l expected=".var_export($e,true)." actual=".var_export($a,true)."\n";}
$table=PGE_Salla_Sync_Schema::table_name();$m=random_int(700000000,749000000);$c=random_int(750000000,799000000);$g=PGE_Salla_Plus_Eligibility_Resolver::GROUP_ID;$tokenKey='pge_salla_tokens_'.$m;$tokenSentinel='__p7_missing__';$oldToken=get_option($tokenKey,$tokenSentinel);$nullIds=[];
try{
 p7m('schema 1.1 installer succeeds',PGE_Salla_Sync_Schema::maybe_upgrade(),true);p7m('schema installer idempotent',PGE_Salla_Sync_Schema::maybe_upgrade(),true);p7m('schema version installed',get_option(PGE_Salla_Sync_Schema::VERSION_OPTION),PGE_Salla_Sync_Schema::SCHEMA_VERSION);
 foreach(['removal_snapshot_groups','removal_snapshot_revision','removal_snapshot_state']as$column)p7m("schema has $column",(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s",$table,$column)),1);
 $made=PGE_Salla_Membership_Sync_Store::request_not_member($m,$c,$g);$id=(int)$made['id'];$ids[]=$id;$claim=PGE_Salla_Membership_Sync_Store::claim($id);p7m('initial claim acquired',$claim['result'],'claimed');p7m('snapshot persists',PGE_Salla_Membership_Sync_Store::save_removal_snapshot($claim,[44,33],'ambiguous')['result'],'saved');$row=PGE_Salla_Membership_Sync_Store::get($id);p7m('snapshot canonical JSON',$row['removal_snapshot_groups'],'[33,44]');p7m('snapshot bound to desired revision',(int)$row['removal_snapshot_revision'],(int)$claim['desired_revision']);
 $wpdb->update($table,['attempt_started_at'=>gmdate('Y-m-d H:i:s',time()-PGE_Salla_Membership_Sync_Store::LEASE_SECONDS-2)],['id'=>$id]);$reclaim=PGE_Salla_Membership_Sync_Store::claim($id);p7m('lease recovery changes attempt token',$reclaim['attempt_token']===$claim['attempt_token'],false);p7m('same revision survives new token',$reclaim['removal_snapshot_groups'],[33,44]);p7m('reclaimed operation reconciles first',$reclaim['reconcile_first'],true);
 update_option($tokenKey,['access_token'=>'local-phase7-token','expires'=>time()+3600],false);$calls=[];$hook=function($pre,$args,$url)use(&$calls){$calls[]=['method'=>$args['method']??'GET','url'=>$url];return['response'=>['code'=>200],'body'=>wp_json_encode(['success'=>true,'data'=>['groups'=>[33,44],'first_name'=>'Local']])];};add_filter('pre_http_request',$hook,10,3);$result=PGE_Salla_Membership_Sync_Worker::process_claim($reclaim);remove_filter('pre_http_request',$hook,10);p7m('lease recovery reconciles removal',$result['result'],'removed');p7m('lease recovery performs GET only',array_column($calls,'method'),['GET']);

 $made2=PGE_Salla_Membership_Sync_Store::request_not_member($m+1,$c+1,$g);$id2=(int)$made2['id'];$ids[]=$id2;$claim2=PGE_Salla_Membership_Sync_Store::claim($id2);PGE_Salla_Membership_Sync_Store::save_removal_snapshot($claim2,[55]);$member=PGE_Salla_Membership_Sync_Store::request_member($m+1,$c+1,$g);$memberRow=PGE_Salla_Membership_Sync_Store::get($id2);p7m('member transition increments revision',(int)$memberRow['desired_revision'],(int)$claim2['desired_revision']+1);p7m('member transition clears snapshot',$memberRow['removal_snapshot_groups'],null);p7m('member transition clears snapshot revision',$memberRow['removal_snapshot_revision'],null);
 p7m('member transition makes old claim stale',PGE_Salla_Membership_Sync_Store::revalidate_claim($claim2)['result'],'stale_claim');$made3=PGE_Salla_Membership_Sync_Store::request_not_member($m+2,$c+2,$g);$id3=(int)$made3['id'];$ids[]=$id3;$made4=PGE_Salla_Membership_Sync_Store::request_member($m+3,$c+3,$g);$id4=(int)$made4['id'];$ids[]=$id4;$beforeAttempts=(int)PGE_Salla_Membership_Sync_Store::get($id3)['attempt_count'];$enabledOnly=PGE_Salla_Membership_Sync_Store::find_due(50,false);p7m('disabled SQL excludes every not_member row',count(array_filter($enabledOnly,static fn($row)=>(string)$row['desired_state']==='not_member')),0);p7m('disabled SQL still includes member row',in_array($id4,array_map(static fn($row)=>(int)$row['id'],$enabledOnly),true),true);p7m('unclaimed disabled attempts unchanged',(int)PGE_Salla_Membership_Sync_Store::get($id3)['attempt_count'],$beforeAttempts);

 $method=new ReflectionMethod(PGE_Salla_Sync_Schema::class,'postconditions_hold');$method->setAccessible(true);$wpdb->query("ALTER TABLE `$table` CHANGE removal_snapshot_state removal_snapshot_state_missing VARCHAR(20) NULL");$renamed=true;p7m('schema validator detects drift',$method->invoke(null),false);p7m('installer repairs drift before accepting version',PGE_Salla_Sync_Schema::maybe_upgrade(),true);$wpdb->query("UPDATE `$table` SET removal_snapshot_state=removal_snapshot_state_missing WHERE removal_snapshot_state IS NULL");$wpdb->query("ALTER TABLE `$table` DROP COLUMN removal_snapshot_state_missing");$renamed=false;p7m('dbDelta repairs drift',(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME='removal_snapshot_state'",$table)),1);
 foreach([['groups type',"ALTER TABLE `$table` MODIFY removal_snapshot_groups MEDIUMTEXT NULL",'longtext'],['revision signed',"ALTER TABLE `$table` MODIFY removal_snapshot_revision BIGINT NULL",'bigint unsigned'],['state length',"ALTER TABLE `$table` MODIFY removal_snapshot_state VARCHAR(10) NULL",'varchar(20)']]as[$label,$alter,$expected]){$wpdb->query($alter);p7m("validator rejects $label drift",$method->invoke(null),false);p7m("installer repairs $label drift",PGE_Salla_Sync_Schema::maybe_upgrade(),true);$field=$label==='groups type'?'removal_snapshot_groups':($label==='revision signed'?'removal_snapshot_revision':'removal_snapshot_state');$type=strtolower((string)$wpdb->get_var($wpdb->prepare("SELECT COLUMN_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME=%s",$table,$field)));p7m("$label restored",$type,$expected);}
 $nullIds=array_map('intval',(array)$wpdb->get_col("SELECT id FROM `$table` WHERE removal_snapshot_state IS NULL"));$wpdb->query("UPDATE `$table` SET removal_snapshot_state='' WHERE removal_snapshot_state IS NULL");$wpdb->query("ALTER TABLE `$table` MODIFY removal_snapshot_state VARCHAR(20) NOT NULL DEFAULT ''");p7m('validator rejects state NOT NULL drift',$method->invoke(null),false);p7m('installer repairs state nullability',PGE_Salla_Sync_Schema::maybe_upgrade(),true);if($nullIds)$wpdb->query("UPDATE `$table` SET removal_snapshot_state=NULL WHERE id IN (".implode(',',$nullIds).")");p7m('state nullability restored',strtoupper((string)$wpdb->get_var($wpdb->prepare("SELECT IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s AND COLUMN_NAME='removal_snapshot_state'",$table))),'YES');
}finally{if($renamed)$wpdb->query("ALTER TABLE `$table` CHANGE removal_snapshot_state_missing removal_snapshot_state VARCHAR(20) NULL");$wpdb->query("ALTER TABLE `$table` MODIFY removal_snapshot_groups LONGTEXT NULL, MODIFY removal_snapshot_revision BIGINT(20) UNSIGNED NULL, MODIFY removal_snapshot_state VARCHAR(20) NULL");if($nullIds)$wpdb->query("UPDATE `$table` SET removal_snapshot_state=NULL WHERE id IN (".implode(',',array_map('intval',$nullIds)).")");foreach($ids as$id)$wpdb->delete($table,['id'=>$id],['%d']);if($oldToken===$tokenSentinel)delete_option($tokenKey);else update_option($tokenKey,$oldToken,false);}
echo"$p/$n passed\n";exit($p===$n?0:1);
