<?php
/** Phase 3 Event Binding contract tests. No real DB or HTTP. */
define('ABSPATH', __DIR__ . '/');
$passed = 0; $failed = 0;
function p3($label, $actual, $expected) { global $passed, $failed; if ($actual === $expected) { $passed++; echo "PASS: $label\n"; } else { $failed++; echo "FAIL: $label expected=" . var_export($expected, true) . " actual=" . var_export($actual, true) . "\n"; } }
class WP_Error { private $code; function __construct($code) { $this->code=$code; } function get_error_code(){return $this->code;} }
function is_wp_error($v){return $v instanceof WP_Error;} function absint($v){return abs((int)$v);} function current_time($t,$g=false){return '2026-09-23 14:00:00';}
$meta=[]; function get_user_meta($u,$k,$s=true){global $meta;return $meta[$u][$k]??'';} function get_post_meta($p,$k,$s=true){global $postmeta;return $postmeta[$p][$k]??'';} function wp_delete_post($p,$force=false){global $deleteFails,$postmeta,$posts;if($deleteFails)return false;unset($postmeta[$p],$posts[$p]);return (object)['ID'=>$p];} function get_posts($args=[]){global $postmeta;$found=[];foreach($postmeta as$id=>$m)if(($m['_pge_event_creation_operation_id']??'')===($args['meta_value']??''))$found[]=(object)['ID'=>$id];return$found;} function get_post_field($field,$id){global$posts;return$posts[$id]['post_author']??0;}
class FakeWpdbP3 { public $last_error='',$fail_start=false,$fail_commit=false,$fail_rollback=false; function query($q){if($q==='START TRANSACTION'&&$this->fail_start)return false;if($q==='COMMIT'&&$this->fail_commit)return false;if($q==='ROLLBACK'&&$this->fail_rollback)return false;return 0;} }
$wpdb=new FakeWpdbP3();
class PGE_Catalog_Activation_Repository { const STATE_ACTIVE_UNBOUND='active_unbound',STATE_ACTIVE_BOUND='active_bound',STATE_ENDED='ended',STATE_REVOKED='revoked'; public static $rows=[],$cas=''; static function find_by_activation_id($a){foreach(self::$rows as $r)if($r['activation_id']===$a)return$r;return null;} static function find_by_id_for_update($id){return self::$rows[$id]??null;} static function find_by_id($id){return self::$rows[$id]??null;} static function compare_and_swap_state($id,$es,$er,$ns,$m=[]){if(self::$cas)return['result'=>self::$cas];$r=self::$rows[$id]??null;if(!$r)return['result'=>'missing'];if(in_array($r['lifecycle_state'],['ended','revoked'],true))return['result'=>'terminal'];if($r['lifecycle_state']!==$es||$r['revision']!==$er)return['result'=>'stale'];self::$rows[$id]['lifecycle_state']=$ns;self::$rows[$id]['revision']++;return['result'=>'updated','revision'=>$er+1];} }
class PGE_Catalog_Event_Binding_Repository { public static $rows=[],$fail=''; static function find_by_activation_id($id){return array_values(array_filter(self::$rows,fn($r)=>(int)$r['catalog_activation_id']===(int)$id));} static function find_by_event_id($id){foreach(self::$rows as$r)if((int)$r['event_id']===(int)$id)return$r;return null;} static function create($aid,$eid,$at=null){if(self::$fail)return['result'=>self::$fail];if(self::find_by_event_id($eid))return['result'=>'conflict'];$r=['id'=>count(self::$rows)+1,'catalog_activation_id'=>$aid,'event_id'=>$eid];self::$rows[]=$r;return['result'=>'created','id'=>$r['id']];} }
require_once dirname(__DIR__).'/includes/class-pge-catalog-event-binding-service.php';
function reset_p3($state='active_unbound',$plan='halwa_plus'){global $wpdb,$meta,$postmeta,$posts,$deleteFails;$deleteFails=false;$wpdb->last_error='';$wpdb->fail_start=$wpdb->fail_commit=$wpdb->fail_rollback=false;$meta=[7=>['_mon_package_source'=>'catalog','_mon_package_status'=>'active','_mon_credit_cycle_id'=>'a-uuid','_mon_catalog_plan_id'=>2,'_mon_catalog_tier_id'=>3]];$postmeta=[];$posts=[];PGE_Catalog_Activation_Repository::$rows=[1=>['id'=>1,'activation_id'=>'a-uuid','user_id'=>7,'plan_id'=>2,'tier_id'=>3,'plan_key'=>$plan,'lifecycle_state'=>$state,'revision'=>2]];PGE_Catalog_Activation_Repository::$cas='';PGE_Catalog_Event_Binding_Repository::$rows=[];PGE_Catalog_Event_Binding_Repository::$fail='';}
reset_p3();$r=PGE_Catalog_Event_Binding_Service::resolve_current(7);p3('current durable activation resolves',$r['result']??'','ready');p3('UUID remains ownership identity',$r['activation']['activation_id']??'','a-uuid');
foreach(['preparing','ended','revoked'] as $state){reset_p3($state);$r=PGE_Catalog_Event_Binding_Service::resolve_current(7);p3("$state fails closed",is_wp_error($r)?$r->get_error_code():'','event_activation_'.$state);}
reset_p3();global $meta;$meta[7]['_mon_credit_cycle_id']='missing';$r=PGE_Catalog_Event_Binding_Service::resolve_current(7);p3('missing durable activation fails closed',is_wp_error($r)?$r->get_error_code():'','event_activation_missing');
reset_p3();$meta[7]['_mon_catalog_tier_id']=9;$r=PGE_Catalog_Event_Binding_Service::resolve_current(7);p3('projection mismatch fails closed',is_wp_error($r)?$r->get_error_code():'','event_activation_mismatch');
reset_p3();global $postmeta;$postmeta[10]['_pge_event_activation_id']='a-uuid';$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p3('fresh event binds',$r['result']??'','bound');p3('binding created once',count(PGE_Catalog_Event_Binding_Repository::$rows),1);p3('activation transitions bound',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'active_bound');
$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p3('same event binding idempotent',$r['result']??'','already_bound');p3('idempotent binding remains one',count(PGE_Catalog_Event_Binding_Repository::$rows),1);
reset_p3();$postmeta[10]['_pge_event_activation_id']='other';$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p3('post meta mismatch rejected',is_wp_error($r)?$r->get_error_code():'','event_activation_meta_mismatch');
reset_p3();$postmeta[10]['_pge_event_activation_id']='a-uuid';PGE_Catalog_Event_Binding_Repository::$rows[]=['id'=>1,'catalog_activation_id'=>99,'event_id'=>10];$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p3('binding conflict rejected',is_wp_error($r)?$r->get_error_code():'','event_binding_conflict');
reset_p3('active_bound');$postmeta[10]['_pge_event_activation_id']='a-uuid';PGE_Catalog_Event_Binding_Repository::$rows[]=['id'=>1,'catalog_activation_id'=>1,'event_id'=>9];$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p3('Plus second event rejected',is_wp_error($r)?$r->get_error_code():'','plus_activation_already_bound');
reset_p3();$postmeta[10]['_pge_event_activation_id']='a-uuid';PGE_Catalog_Activation_Repository::$cas='stale';$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p3('unproven stale CAS rejected',is_wp_error($r)?$r->get_error_code():'','event_binding_cas_stale');
reset_p3();$postmeta[10]['_pge_event_activation_id']='a-uuid';PGE_Catalog_Event_Binding_Repository::$fail='db_error';$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],10);p3('binding DB error classified',is_wp_error($r)?$r->get_error_code():'','event_binding_db_error');
reset_p3('active_bound','standard');$postmeta[10]['_pge_event_activation_id']=$postmeta[11]['_pge_event_activation_id']='a-uuid';PGE_Catalog_Event_Binding_Repository::$rows[]=['id'=>1,'catalog_activation_id'=>1,'event_id'=>10];$r=PGE_Catalog_Event_Binding_Service::bind_event(PGE_Catalog_Activation_Repository::$rows[1],11);p3('non-Plus activation permits another binding',$r['result']??'','bound');p3('non-Plus has two durable bindings',count(PGE_Catalog_Event_Binding_Repository::$rows),2);
reset_p3('active_bound');PGE_Catalog_Event_Binding_Repository::$rows[]=['id'=>1,'catalog_activation_id'=>1,'event_id'=>10];$r=PGE_Catalog_Event_Binding_Service::resolve_current(7);p3('binding with missing ownership meta fails closed',is_wp_error($r)?$r->get_error_code():'','event_binding_ownership_mismatch');
$op='11111111-1111-4111-8111-111111111111';reset_p3();$postmeta[10]=['_pge_event_activation_id'=>'a-uuid','_pge_event_creation_operation_id'=>$op];$r=PGE_Catalog_Event_Binding_Service::compensate_new_event(10,'a-uuid',$op,true);p3('failed binding compensation deletes owned new event',$r['result'],'compensated');p3('compensation removed post data',isset($postmeta[10]),false);
reset_p3();$postmeta[10]=['_pge_event_activation_id'=>'a-uuid','_pge_event_creation_operation_id'=>$op];$deleteFails=true;$r=PGE_Catalog_Event_Binding_Service::compensate_new_event(10,'a-uuid',$op,true);p3('compensation delete failure is explicit',$r['result'],'recovery_incident');p3('failed compensation preserves ownership meta',$postmeta[10]['_pge_event_activation_id'],'a-uuid');
reset_p3();$posts[10]=['post_author'=>7];$postmeta[10]=['_pge_event_activation_id'=>'a-uuid','_pge_event_creation_operation_id'=>$op];$r=PGE_Catalog_Event_Binding_Service::resolve_creation_operation(PGE_Catalog_Activation_Repository::$rows[1],7,$op);p3('operation retry finds same event',$r['result']??'','existing');p3('operation retry returns same event',(int)($r['event_id']??0),10);
$r=PGE_Catalog_Event_Binding_Service::resolve_creation_operation(PGE_Catalog_Activation_Repository::$rows[1],8,$op);p3('operation user collision rejected',is_wp_error($r)?$r->get_error_code():'','event_creation_operation_conflict');
reset_p3();$posts[10]=['post_author'=>7];$postmeta[10]=['_pge_event_activation_id'=>'other','_pge_event_creation_operation_id'=>$op];$r=PGE_Catalog_Event_Binding_Service::resolve_creation_operation(PGE_Catalog_Activation_Repository::$rows[1],7,$op);p3('operation activation collision rejected',is_wp_error($r)?$r->get_error_code():'','event_creation_operation_conflict');
reset_p3();$posts[10]=['post_author'=>7];$postmeta[10]=['_pge_event_activation_id'=>'a-uuid','_pge_event_creation_operation_id'=>$op];$r=PGE_Catalog_Event_Binding_Service::compensate_new_event(10,'a-uuid',$op,false);p3('recovered event cannot be compensated',$r['result']??'','not_created_here');p3('recovered event remains',isset($posts[10]),true);
reset_p3();$r=PGE_Catalog_Event_Binding_Service::resolve_creation_operation(PGE_Catalog_Activation_Repository::$rows[1],7,'not-a-uuid');p3('invalid operation UUID rejected',is_wp_error($r)?$r->get_error_code():'','event_creation_operation_invalid');
reset_p3();$posts[10]=['post_author'=>7];$posts[11]=['post_author'=>7];$postmeta[10]=['_pge_event_activation_id'=>'a-uuid','_pge_event_creation_operation_id'=>$op];$postmeta[11]=$postmeta[10];$r=PGE_Catalog_Event_Binding_Service::resolve_creation_operation(PGE_Catalog_Activation_Repository::$rows[1],7,$op);p3('duplicate operation rows conflict',is_wp_error($r)?$r->get_error_code():'','event_creation_operation_conflict');
reset_p3();$posts[10]=['post_author'=>7];$postmeta[10]=['_pge_event_activation_id'=>'a-uuid','_pge_event_creation_operation_id'=>$op];$r=PGE_Catalog_Event_Binding_Service::compensate_new_event(10,'a-uuid','22222222-2222-4222-8222-222222222222',true);p3('compensation operation mismatch is incident',$r['result']??'','recovery_incident');p3('operation mismatch preserves event',isset($posts[10]),true);
echo "\n$passed passed, $failed failed\n"; exit($failed?1:0);
