<?php
/** Local MySQL proof for Phase 2 uniqueness and CAS primitives. */
$root=dirname(__DIR__,4);$_SERVER['REQUEST_SCHEME']='https';$_SERVER['HTTP_HOST']='monasbat.test';require_once $root.'/wp-load.php';
$site=(string)get_option('siteurl','');$local=defined('DB_NAME')&&DB_NAME==='monasbat'&&preg_match('#^https?://[^/]+\.test(?:/|$)#',$site)&&stripos(str_replace('\\','/',$root),'/laragon/www/monasbat')!==false&&function_exists('wp_get_environment_type')&&wp_get_environment_type()!=='production';if(!$local){fwrite(STDERR,"ABORT: local guard failed; no writes.\n");exit(2);}global $wpdb;$pass=0;$total=0;function p2mysql($l,$a,$e){global $pass,$total;$total++;if($a===$e){$pass++;echo"PASS: $l\n";}else echo"FAIL: $l expected=".var_export($e,true)." actual=".var_export($a,true)."\n";}
$tag='phase2-it-'.bin2hex(random_bytes(6));$ids=[];$dbids=[];$testUser=0;$testPlan=0;$testTier=0;
try{
 $lock='pge_catalog_activation_user_910000001';
 p2mysql('first connection acquires per-user lock',(int)$wpdb->get_var($wpdb->prepare('SELECT GET_LOCK(%s, %d)',$lock,0)),1);
 $hostParts=explode(':',DB_HOST,2);$mysqli=@new mysqli($hostParts[0],DB_USER,DB_PASSWORD,DB_NAME,isset($hostParts[1])?(int)$hostParts[1]:3306);
 if($mysqli->connect_errno){throw new RuntimeException('Unable to open second local MySQL connection');}
 $escaped=$mysqli->real_escape_string($lock);$lockResult=$mysqli->query("SELECT GET_LOCK('{$escaped}',0) AS acquired")->fetch_assoc();
 p2mysql('concurrent connection cannot enter same user saga',(int)$lockResult['acquired'],0);
 $wpdb->query($wpdb->prepare('SELECT RELEASE_LOCK(%s)',$lock));
 $lockResult=$mysqli->query("SELECT GET_LOCK('{$escaped}',0) AS acquired")->fetch_assoc();p2mysql('second connection acquires after release',(int)$lockResult['acquired'],1);$mysqli->query("SELECT RELEASE_LOCK('{$escaped}')");$mysqli->close();
 $mk=function($aid,$idem,$source='manual',$order=null)use(&$ids){$ids[]=$aid;return PGE_Catalog_Activation_Repository::create_preparing(['activation_id'=>$aid,'user_id'=>910000001,'plan_id'=>910000002,'tier_id'=>910000003,'plan_key'=>'halwa_plus','tier_key'=>'guests_100','activation_source'=>$source,'idempotency_key'=>$idem,'external_order_id'=>$order,'projection_snapshot'=>'{"meta":{"_mon_credit_cycle_id":"'.$aid.'"},"delete":[]}']);};
 $a=$mk($tag.'-a','manual:11111111-1111-4111-8111-111111111111');p2mysql('manual preparing created',$a['result']??null,'created');$dbids[]=(int)$a['id'];$dup=$mk($tag.'-dup','manual:11111111-1111-4111-8111-111111111111');p2mysql('same manual key unique',$dup['reason']??null,'idempotency_key');p2mysql('same key resolves original',(int)($dup['record']['id']??0),(int)$a['id']);
 $cas=PGE_Catalog_Activation_Repository::compare_and_swap_state((int)$a['id'],'preparing',1,'active_unbound');p2mysql('CAS activates',$cas['result']??null,'updated');$stale=PGE_Catalog_Activation_Repository::compare_and_swap_state((int)$a['id'],'preparing',1,'active_unbound');p2mysql('stale CAS rejected',$stale['result']??null,'stale');
 $order=$tag.'-order';$s=$mk($tag.'-s','salla:392732220:'.$order,'salla',$order);p2mysql('Salla preparing created',$s['result']??null,'created');$dbids[]=(int)$s['id'];$o=PGE_Catalog_Provider_Origin_Repository::create((int)$s['id'],'salla',392732220,'1888007575',$order);p2mysql('provider origin created',$o['result']??null,'created');$od=PGE_Catalog_Provider_Origin_Repository::create((int)$s['id'],'salla',392732220,'1888007575',$order);p2mysql('provider order unique',$od['reason']??null,'provider_order');p2mysql('one origin physically',(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM '.PGE_Catalog_Activation_Schema::origins_table().' WHERE provider=%s AND merchant_id=%d AND external_order_id=%s','salla',392732220,$order)),1);
 $testUser=wp_insert_user(['user_login'=>$tag,'user_pass'=>wp_generate_password(24,true,true),'user_email'=>$tag.'@example.test']);
 $plan=PGE_Catalog::create_plan(['plan_key'=>$tag,'name'=>'Phase 2 integration','plan_type'=>'personal','status'=>'active','sort_order'=>0,'features'=>[]]);$testPlan=(int)($plan['id']??0);
 $wpdb->insert($wpdb->prefix.'mon_plan_tiers',['plan_id'=>$testPlan,'tier_key'=>'integration','name'=>'Integration','price'=>'10','currency'=>'SAR','status'=>'active','sort_order'=>0,'invitation_credit_limit'=>5,'replacement_credit_limit'=>3,'event_quota_mode'=>'limited','event_quota_limit'=>1],['%d','%s','%s','%s','%s','%s','%d','%d','%d','%s','%d']);$testTier=(int)$wpdb->insert_id;$tier=PGE_Catalog::get_tier($testTier);
 p2mysql('production fixtures created',is_wp_error($testUser)||!$testPlan||!$testTier?0:1,1);
 p2mysql('production tier fixture active',$tier['status']??null,'active');
 if(!is_wp_error($testUser)&&$testPlan&&$testTier){$operation=wp_generate_uuid4();$live=PGE_Catalog_Activation_Service::activate((int)$testUser,$testPlan,$testTier,['source'=>'manual','operation_id'=>$operation]);p2mysql('production service fresh activation',is_wp_error($live)?$live->get_error_code():($live['result']??null),'activated');if(!is_wp_error($live)){$liveRow=PGE_Catalog_Activation_Repository::find_by_id((int)($live['catalog_activation_id']??0));p2mysql('production durable row active',$liveRow['lifecycle_state']??null,'active_unbound');$stored=json_decode((string)($liveRow['projection_snapshot']??''),true);p2mysql('stored snapshot separates mutable credits',isset($stored['credit_cycle']['initial_used'])&&!isset($stored['meta']['_mon_invitation_credit_used']),true);p2mysql('production User Meta cycle matches durable activation',get_user_meta((int)$testUser,'_mon_credit_cycle_id',true),$live['activation_id']);$replay=PGE_Catalog_Activation_Service::activate((int)$testUser,$testPlan,$testTier,['source'=>'manual','operation_id'=>$operation]);p2mysql('production same-key replay',$replay['result']??null,'replayed');$ids[]=$live['activation_id'];$dbids[]=(int)$live['catalog_activation_id'];}}
}finally{$wpdb->query($wpdb->prepare('SELECT RELEASE_LOCK(%s)','pge_catalog_activation_user_910000001'));foreach($dbids as $id)$wpdb->delete(PGE_Catalog_Activation_Schema::origins_table(),['catalog_activation_id'=>$id],['%d']);foreach(array_unique($ids) as $id)$wpdb->delete(PGE_Catalog_Activation_Schema::activations_table(),['activation_id'=>$id],['%s']);if($testTier)PGE_Catalog::delete_tier($testTier);if($testPlan)PGE_Catalog::delete_plan($testPlan);if($testUser&&!is_wp_error($testUser)){require_once ABSPATH.'wp-admin/includes/user.php';wp_delete_user((int)$testUser);}}
echo"\n$pass/$total passed\n";exit($pass===$total?0:1);
