<?php
define('ABSPATH',__DIR__.'/');$GLOBALS['p8_option']=null;
function get_option($k,$d=null){return $k==='pge_salla_not_member_removal_enabled'?$GLOBALS['p8_option']:$d;}
class WP_Error{private$c,$d;function __construct($c,$m='',$d=null){$this->c=$c;$this->d=$d;}function get_error_code(){return$this->c;}function get_error_data(){return$this->d;}}
function is_wp_error($v){return$v instanceof WP_Error;}function current_time($k,$g=false){return$k==='timestamp'?1700000000:'2023-11-14 22:13:20';}function add_action(){}function wp_next_scheduled(){return false;}function wp_schedule_single_event(){return true;}
class P8DB{function prepare($q,...$a){return$q;}function get_var($q){return 1;}function query($q){return 1;}}$GLOBALS['wpdb']=new P8DB();
require dirname(__DIR__).'/includes/class-pge-salla-not-member-removal-feature.php';
class PGE_Salla_Membership_Sync_Store{const DESIRED_MEMBER='member',DESIRED_NOT_MEMBER='not_member';static$marks=[],$snapshot=null,$state='',$valid=true,$stale_on_save=false;static function identity_lock_name(...$x){return'l';}static function revalidate_claim($c){return self::$valid?['result'=>'valid','row'=>[]]:['result'=>'stale_claim'];}static function removal_snapshot($c){return self::$snapshot===null?['result'=>'none']:['result'=>'found','groups'=>self::$snapshot,'state'=>self::$state];}static function save_removal_snapshot($c,$g,$s='prepared'){if(self::$stale_on_save){self::$valid=false;return['result'=>'stale_claim'];}self::$snapshot=$g;self::$state=$s;return['result'=>'saved'];}static function request_state_locked(...$x){self::$valid=false;return['result'=>'updated'];}static function mark_satisfied($c){self::$marks[]=['satisfied'];return true;}static function mark_retry($c,$e,$d,$a=false){self::$marks[]=['retry',$e];return true;}static function mark_failed($c,$e){self::$marks[]=['failed',$e];return true;}static function reset(){self::$marks=[];self::$snapshot=null;self::$state='';self::$valid=true;self::$stale_on_save=false;}}
class PGE_Salla_Plus_Eligibility_Resolver{static$toggle=false;static function resolve($m,$c){if(self::$toggle)$GLOBALS['p8_option']=0;return['authoritative'=>true,'eligible'=>false];}}
class PGE_Salla_Customer_Groups_Service{static$gets=[],$puts=0,$adds=0,$disable_on_get=false,$disable_on_put=false,$put_result=['success'=>true];function get_customer_details($m,$c){if(self::$disable_on_get)$GLOBALS['p8_option']=0;return array_shift(self::$gets);}function update_customer_groups(...$x){self::$puts++;if(self::$disable_on_put)$GLOBALS['p8_option']=0;return self::$put_result;}function add_customer_to_group(...$x){self::$adds++;return['success'=>true];}function customer_is_in_group(...$x){return['is_member'=>false];}static function reset(){self::$gets=[];self::$puts=0;self::$adds=0;self::$disable_on_get=false;self::$disable_on_put=false;self::$put_result=['success'=>true];}}
require dirname(__DIR__).'/includes/class-pge-salla-membership-sync-worker.php';
$p=0;$n=0;function p8($l,$a,$e){global$p,$n;$n++;if($a===$e){$p++;echo"PASS $l\n";}else echo"FAIL $l expected=".var_export($e,true)." actual=".var_export($a,true)."\n";}function c8($state='not_member'){return['id'=>1,'desired_state'=>$state,'desired_revision'=>1,'attempt_revision'=>1,'attempt_token'=>'t','merchant_id'=>1,'salla_customer_id'=>2,'group_id'=>225189340,'attempt_count'=>1,'reconcile_first'=>false,'removal_snapshot_groups'=>null,'removal_snapshot_state'=>''];}function r8(){PGE_Salla_Membership_Sync_Store::reset();PGE_Salla_Customer_Groups_Service::reset();PGE_Salla_Plus_Eligibility_Resolver::$toggle=false;}
foreach([[null,false],[false,false],[0,false],['0',false],['true',false],['yes',false],[[],false],[1,true],['1',true],[true,true]]as[$v,$e]){$GLOBALS['p8_option']=$v;p8('strict flag '.var_export($v,true),PGE_Salla_Not_Member_Removal_Feature::enabled(),$e);}
r8();$GLOBALS['p8_option']=0;$x=PGE_Salla_Membership_Sync_Worker::process_claim(c8());p8('disabled branch deferred',$x['result'],'removal_disabled');p8('disabled branch no HTTP',[count(PGE_Salla_Customer_Groups_Service::$gets),PGE_Salla_Customer_Groups_Service::$puts],[0,0]);p8('disabled branch retry mark',PGE_Salla_Membership_Sync_Store::$marks[0],['retry','removal_disabled']);
r8();$GLOBALS['p8_option']=1;PGE_Salla_Plus_Eligibility_Resolver::$toggle=true;$x=PGE_Salla_Membership_Sync_Worker::process_claim(c8());p8('disable after lock prevents HTTP',$x['result'],'removal_disabled');p8('after lock PUT zero',PGE_Salla_Customer_Groups_Service::$puts,0);
r8();$GLOBALS['p8_option']=1;PGE_Salla_Customer_Groups_Service::$disable_on_get=true;PGE_Salla_Customer_Groups_Service::$gets=[['exists'=>true,'groups'=>[225189340,8],'first_name'=>'N']];$x=PGE_Salla_Membership_Sync_Worker::process_claim(c8());p8('disable immediately before PUT deferred',$x['result'],'removal_disabled');p8('immediate pre-PUT guard zero',PGE_Salla_Customer_Groups_Service::$puts,0);p8('snapshot preserved',PGE_Salla_Membership_Sync_Store::$snapshot,[8]);
r8();$GLOBALS['p8_option']=0;PGE_Salla_Membership_Sync_Store::$snapshot=[8];PGE_Salla_Membership_Sync_Store::$state='ambiguous';PGE_Salla_Customer_Groups_Service::$gets=[['exists'=>true,'groups'=>[8],'first_name'=>'N']];$c=c8();$c['reconcile_first']=true;$c['removal_snapshot_groups']=[8];$c['removal_snapshot_state']='ambiguous';$x=PGE_Salla_Membership_Sync_Worker::process_claim($c);p8('disabled ambiguous reconciles success',$x['result'],'removed');p8('disabled ambiguity no PUT',PGE_Salla_Customer_Groups_Service::$puts,0);
r8();$GLOBALS['p8_option']=0;PGE_Salla_Membership_Sync_Store::$snapshot=[8];PGE_Salla_Membership_Sync_Store::$state='ambiguous';PGE_Salla_Customer_Groups_Service::$gets=[['exists'=>true,'groups'=>[225189340,8],'first_name'=>'N']];$c=c8();$c['reconcile_first']=true;$c['removal_snapshot_groups']=[8];$c['removal_snapshot_state']='ambiguous';$x=PGE_Salla_Membership_Sync_Worker::process_claim($c);p8('disabled target present deferred',$x['result'],'removal_disabled');p8('disabled target no replay',PGE_Salla_Customer_Groups_Service::$puts,0);
p8('disabled resolved ambiguity becomes retryable',PGE_Salla_Membership_Sync_Store::$state,'retryable');
r8();$GLOBALS['p8_option']=0;PGE_Salla_Membership_Sync_Store::$snapshot=[8];PGE_Salla_Membership_Sync_Store::$state='ambiguous';PGE_Salla_Customer_Groups_Service::$gets=[new WP_Error('salla_customer_details_transport_error')];$c=c8();$c['reconcile_first']=true;$c['removal_snapshot_groups']=[8];$c['removal_snapshot_state']='ambiguous';$x=PGE_Salla_Membership_Sync_Worker::process_claim($c);p8('unavailable reconciliation remains ambiguous',PGE_Salla_Membership_Sync_Store::$state,'ambiguous');p8('unavailable reconciliation retries ambiguously',PGE_Salla_Membership_Sync_Store::$marks[0],['retry','reconciliation_unavailable']);
r8();$GLOBALS['p8_option']=0;PGE_Salla_Membership_Sync_Store::$snapshot=[8];PGE_Salla_Membership_Sync_Store::$state='ambiguous';PGE_Salla_Customer_Groups_Service::$gets=[['exists'=>true,'groups'=>[225189340],'first_name'=>'N']];$c=c8();$c['reconcile_first']=true;$c['removal_snapshot_groups']=[8];$c['removal_snapshot_state']='ambiguous';$x=PGE_Salla_Membership_Sync_Worker::process_claim($c);p8('preservation conflict remains ambiguous',PGE_Salla_Membership_Sync_Store::$state,'ambiguous');p8('preservation conflict fails closed',$x['result'],'reconciliation_conflict');
r8();$GLOBALS['p8_option']=0;PGE_Salla_Membership_Sync_Store::$snapshot=[8];PGE_Salla_Membership_Sync_Store::$state='ambiguous';PGE_Salla_Membership_Sync_Store::$stale_on_save=true;PGE_Salla_Customer_Groups_Service::$gets=[['exists'=>true,'groups'=>[225189340,8],'first_name'=>'N']];$c=c8();$c['reconcile_first']=true;$c['removal_snapshot_groups']=[8];$c['removal_snapshot_state']='ambiguous';$x=PGE_Salla_Membership_Sync_Worker::process_claim($c);p8('stale snapshot transition is not removal-disabled success',$x['result'],'stale_finalization');p8('stale snapshot transition performs no PUT',PGE_Salla_Customer_Groups_Service::$puts,0);
r8();$GLOBALS['p8_option']=1;PGE_Salla_Customer_Groups_Service::$disable_on_put=true;PGE_Salla_Customer_Groups_Service::$put_result=new WP_Error('salla_customer_update_transport_error');PGE_Salla_Customer_Groups_Service::$gets=[['exists'=>true,'groups'=>[225189340,8],'first_name'=>'N'],['exists'=>true,'groups'=>[8],'first_name'=>'N']];$x=PGE_Salla_Membership_Sync_Worker::process_claim(c8());p8('disable after ambiguous PUT still reconciles',$x['result'],'removed');p8('disable after PUT sends one PUT',PGE_Salla_Customer_Groups_Service::$puts,1);p8('disable after PUT performs reconciliation GET',count(PGE_Salla_Customer_Groups_Service::$gets),0);
r8();$GLOBALS['p8_option']=0;$x=PGE_Salla_Membership_Sync_Worker::process_claim(c8('member'));p8('member works while removal disabled',$x['result'],'satisfied');p8('member add called',PGE_Salla_Customer_Groups_Service::$adds,1);
echo"$p/$n passed\n";exit($p===$n?0:1);
