<?php
/** Standalone Phase 2 Activation Saga tests. No real DB or HTTP. */
define('ABSPATH', __DIR__ . '/');
$passed=0;$failed=0;
function p2($label,$actual,$expected){global $passed,$failed;if($actual===$expected){$passed++;echo "PASS: $label\n";}else{$failed++;echo "FAIL: $label expected=".var_export($expected,true)." actual=".var_export($actual,true)."\n";}}
class WP_Error {private $code,$message;function __construct($c,$m=''){$this->code=$c;$this->message=$m;}function get_error_code(){return $this->code;}function get_error_message(){return $this->message;}}
function is_wp_error($v){return $v instanceof WP_Error;} function absint($v){return abs((int)$v);} function current_time($t,$g=false){return '2026-09-23 12:00:00';} function wp_json_encode($v,$f=0){return json_encode($v,$f);} function get_user_by($f,$id){return $id>0?(object)['ID'=>$id]:false;}
class FakeWpdbP2 {public $last_error='';public $insert_id=0;public $locks=[],$fail_start=false,$fail_commit=false,$fail_rollback=false;function prepare($q,...$a){foreach($a as $v)$q=preg_replace('/%[sd]/',is_numeric($v)?(string)$v:"'".$v."'",$q,1);return $q;}function get_var($q){if(strpos($q,'GET_LOCK')!==false){preg_match("/'([^']+)'/",$q,$m);if(!empty($this->locks[$m[1]]))return 0;$this->locks[$m[1]]=1;return 1;}return null;}function query($q){if($q==='START TRANSACTION'&&$this->fail_start)return false;if($q==='COMMIT'&&$this->fail_commit)return false;if($q==='ROLLBACK'&&$this->fail_rollback)return false;if(strpos($q,'RELEASE_LOCK')!==false){preg_match("/'([^']+)'/",$q,$m);unset($this->locks[$m[1]]);}return 0;}}
$wpdb=new FakeWpdbP2();
class PGE_Catalog_Activation_Repository {const STATE_PREPARING='preparing',STATE_ACTIVE_UNBOUND='active_unbound',STATE_ACTIVE_BOUND='active_bound',STATE_ENDED='ended',STATE_REVOKED='revoked';public static $rows=[],$next=1,$fail_create=false,$stale_cas=false,$forced_cas='';
 static function find_by_idempotency_key($k){foreach(self::$rows as $r)if($r['idempotency_key']===$k)return $r;return null;} static function find_by_id($id){return self::$rows[$id]??null;}
 static function find_by_id_for_update($id){return self::find_by_id($id);}
 static function create_preparing($a){if(self::$fail_create)return ['result'=>'db_error'];$existing=self::find_by_idempotency_key($a['idempotency_key']);if($existing)return ['result'=>'conflict','reason'=>'idempotency_key','record'=>$existing];$id=self::$next++;$r=$a+['id'=>$id,'lifecycle_state'=>'preparing','revision'=>1,'projection_attempts'=>0];self::$rows[$id]=$r;return ['result'=>'created','id'=>$id];}
 static function compare_and_swap_state($id,$es,$er,$ns,$m=[]){if(self::$forced_cas)return ['result'=>self::$forced_cas];if(self::$stale_cas)return ['result'=>'stale'];$r=self::$rows[$id]??null;if(!$r)return ['result'=>'missing'];if(in_array($r['lifecycle_state'],['ended','revoked'],true))return ['result'=>'terminal'];if($r['lifecycle_state']!==$es||$r['revision']!==$er)return ['result'=>'stale'];self::$rows[$id]['lifecycle_state']=$ns;self::$rows[$id]['revision']=$er+1;return ['result'=>'updated','revision'=>$er+1];}
 static function record_projection_failure($id,$rev,$code,$next){if(!isset(self::$rows[$id]))return ['result'=>'missing'];if(self::$rows[$id]['revision']!==$rev)return ['result'=>'stale'];self::$rows[$id]['projection_attempts']++;self::$rows[$id]['last_error_code']=$code;self::$rows[$id]['revision']++;return ['result'=>'recorded','revision'=>$rev+1];}}
class PGE_Catalog_Provider_Origin_Repository {public static $rows=[];static function create($aid,$p,$m,$c,$o){$key="$p:$m:$o";if(isset(self::$rows[$key]))return ['result'=>'conflict','reason'=>'provider_order','record'=>self::$rows[$key]];self::$rows[$key]=['catalog_activation_id'=>$aid,'provider'=>$p,'merchant_id'=>$m,'external_customer_id'=>$c,'external_order_id'=>$o];return ['result'=>'created','id'=>count(self::$rows)];}static function find_by_order($p,$m,$o){return self::$rows["$p:$m:$o"]??null;}static function find_by_activation_and_provider($aid,$p){foreach(self::$rows as $r)if($r['catalog_activation_id']===$aid&&$r['provider']===$p)return $r;return null;}}
class Mon_Events_Users {public static $seq=0,$applied=[],$fail_apply=false,$tierVersion='v1';static function generate_catalog_activation_id(){self::$seq++;return sprintf('00000000-0000-4000-8000-%012d',self::$seq);}static function build_catalog_activation_projection($u,$p,$t,$o,$a){return ['meta'=>['_mon_catalog_plan_id'=>$p,'_mon_catalog_tier_id'=>$t,'_mon_credit_cycle_id'=>$a,'_mon_last_order_id'=>$o,'tier_config'=>self::$tierVersion],'delete'=>[]];}static function apply_catalog_activation_projection($u,array $p){if(self::$fail_apply)return new WP_Error('meta_update_failed');self::$applied[]=$p;return true;}}
require_once dirname(__DIR__).'/includes/class-pge-catalog-activation-service.php';
function reset_p2(){global $wpdb;PGE_Catalog_Activation_Repository::$rows=[];PGE_Catalog_Activation_Repository::$next=1;PGE_Catalog_Activation_Repository::$fail_create=false;PGE_Catalog_Activation_Repository::$stale_cas=false;PGE_Catalog_Activation_Repository::$forced_cas='';PGE_Catalog_Provider_Origin_Repository::$rows=[];Mon_Events_Users::$seq=0;Mon_Events_Users::$applied=[];Mon_Events_Users::$fail_apply=false;Mon_Events_Users::$tierVersion='v1';$wpdb->fail_start=$wpdb->fail_commit=$wpdb->fail_rollback=false;}
$uuid='11111111-1111-4111-8111-111111111111';
reset_p2();$r=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2('fresh manual activates',$r['result']??null,'activated');p2('starts then ends active_unbound',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'active_unbound');p2('activation id equals credit cycle',$r['activation_id'],Mon_Events_Users::$applied[0]['meta']['_mon_credit_cycle_id']);p2('manual creates no origin',count(PGE_Catalog_Provider_Origin_Repository::$rows),0);p2('revision CAS once',PGE_Catalog_Activation_Repository::$rows[1]['revision'],2);
$r2=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2('manual replay',$r2['result'],'replayed');p2('replay creates no activation',count(PGE_Catalog_Activation_Repository::$rows),1);p2('replay does not reproject',count(Mon_Events_Users::$applied),1);
foreach([['user',8,2,3],['plan',7,9,3],['tier',7,2,9]] as $c){$x=PGE_Catalog_Activation_Service::activate($c[1],$c[2],$c[3],['source'=>'manual','operation_id'=>$uuid]);p2($c[0].' mismatch conflict',is_wp_error($x)?$x->get_error_code():'','idempotency_conflict');}p2('mismatch leaves original',count(PGE_Catalog_Activation_Repository::$rows),1);
reset_p2();$s=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'salla','merchant_id'=>99,'external_customer_id'=>'55','external_order_id'=>'ORD-1']);p2('fresh Salla activates',$s['result'],'activated');p2('Salla origin created',count(PGE_Catalog_Provider_Origin_Repository::$rows),1);$s2=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'salla','merchant_id'=>99,'external_customer_id'=>'55','external_order_id'=>'ORD-1']);p2('Salla replay',$s2['result'],'replayed');p2('Salla origin remains unique',count(PGE_Catalog_Provider_Origin_Repository::$rows),1);
reset_p2();Mon_Events_Users::$fail_apply=true;$f=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2('projection failure returned',is_wp_error($f)?$f->get_error_code():'','meta_update_failed');p2('failure remains preparing',PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state'],'preparing');p2('failure attempts once',PGE_Catalog_Activation_Repository::$rows[1]['projection_attempts'],1);$aid=PGE_Catalog_Activation_Repository::$rows[1]['activation_id'];Mon_Events_Users::$tierVersion='v2';Mon_Events_Users::$fail_apply=false;$resume=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2('preparing resumes',$resume['result'],'resumed');p2('resume same activation id',$resume['activation_id'],$aid);p2('resume exact stored snapshot',end(Mon_Events_Users::$applied)['meta']['tier_config'],'v1');
foreach(['ended','revoked'] as $terminal){reset_p2();$x=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);PGE_Catalog_Activation_Repository::$rows[1]['lifecycle_state']=$terminal;$x=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2("$terminal terminal replay",$x['result'],'terminal_replay');p2("$terminal no new activation",count(PGE_Catalog_Activation_Repository::$rows),1);}
reset_p2();PGE_Catalog_Activation_Repository::$fail_create=true;$d=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2('DB error not conflict',is_wp_error($d)?$d->get_error_code():'','activation_db_error');
reset_p2();PGE_Catalog_Activation_Repository::$stale_cas=true;$stale=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2('CAS stale reported',is_wp_error($stale)?$stale->get_error_code():'','activation_cas_stale');p2('CAS stale creates one activation only',count(PGE_Catalog_Activation_Repository::$rows),1);p2('CAS stale keeps same cycle',PGE_Catalog_Activation_Repository::$rows[1]['activation_id'],Mon_Events_Users::$applied[0]['meta']['_mon_credit_cycle_id']);
reset_p2();Mon_Events_Users::$fail_apply=true;$verify=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2('read-back/apply verification failure recorded',PGE_Catalog_Activation_Repository::$rows[1]['last_error_code'],'meta_update_failed');
reset_p2();$bad=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>'bad']);p2('invalid manual operation rejected',is_wp_error($bad)?$bad->get_error_code():'','invalid_operation_id');
reset_p2();$badSalla=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'salla','merchant_id'=>99,'external_customer_id'=>'','external_order_id'=>'ORD']);p2('incomplete Salla origin rejected',is_wp_error($badSalla)?$badSalla->get_error_code():'','invalid_salla_origin');
reset_p2();$wpdb->fail_start=true;$x=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2('START failure is explicit',is_wp_error($x)?$x->get_error_code():'','activation_storage_unavailable');p2('START failure does not insert',count(PGE_Catalog_Activation_Repository::$rows),0);p2('START failure does not project',count(Mon_Events_Users::$applied),0);
reset_p2();$wpdb->fail_commit=true;$x=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2('COMMIT failure is uncertain',is_wp_error($x)?$x->get_error_code():'','activation_storage_uncertain');p2('COMMIT failure does not project',count(Mon_Events_Users::$applied),0);
reset_p2();PGE_Catalog_Activation_Repository::$fail_create=true;$wpdb->fail_rollback=true;$x=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2('ROLLBACK failure is uncertain',is_wp_error($x)?$x->get_error_code():'','activation_storage_uncertain');
foreach(['stale','missing','terminal','db_error'] as $casResult){reset_p2();PGE_Catalog_Activation_Repository::$forced_cas=$casResult;$x=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'manual','operation_id'=>$uuid]);p2("CAS $casResult is explicit",is_wp_error($x)?$x->get_error_code():'','activation_cas_'.$casResult);}
reset_p2();Mon_Events_Users::$fail_apply=true;$x=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'salla','merchant_id'=>99,'external_customer_id'=>'55','external_order_id'=>'REPAIR']);PGE_Catalog_Provider_Origin_Repository::$rows=[];Mon_Events_Users::$fail_apply=false;$x=PGE_Catalog_Activation_Service::activate(7,2,3,['source'=>'salla','merchant_id'=>99,'external_customer_id'=>'55','external_order_id'=>'REPAIR']);p2('missing preparing origin repaired',$x['result']??'','resumed');p2('repaired origin persisted',count(PGE_Catalog_Provider_Origin_Repository::$rows),1);
echo "\n$passed passed, $failed failed\n";exit($failed?1:0);
